### ISSUE TITLE
Sequelize sync() 통해 table 생성 시 table 이름이 소문자로 생성됨

### ISSUE THREAD

**Issue by bkkmw** [Flow-PDA/Server#3]
기본 설정이 소문자 생성 같은데 설정을 바꾸거나 DB table이름을 소문자로 해야 할 것 같습니다.

**Comment by chanjin1998** [comment]
"tableName: 실제 데이터베이스의 테이블 이름. 기본적으로 모델 이름의 소문자 및 복수형으로 만든다. 예를 들어 모델 이름이 User 라면 테이블 이름은 users 이다" 라고 하네요,,,,

**Comment by bkkmw** [comment]
`sync( {alter : true})` 사용시 table간 foreign key constraints 비교 과정에서 대소문자 구분하는 문제가 있어 table 이름을 소문자로 변경하였습니다.
